###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts?owner=Daniel

###

GET http://localhost:3000/posts/673a31c1d2b1e95d3407fbef 

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner":"Daniel",
    "title":"My Second post",
    "content": "hello"
}

####

DELETE http://localhost:3000/posts/123
